#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'rubygems'
require 'bundler/setup'
require 'dcell'
require 'vnet'

def success(msg)
  puts "\e[32mSUCCESS:\e[0m #{msg}"
end

def failure(msg, err = nil)
  output = "\e[31mFAILURE:\e[0m #{msg}"
  output = output + "\n         #{err.class}: #{err.message}" if err

  puts output
end

conf = Vnet::Configurations::Common.conf

params = {
  :id => 'vndoctor',
  #TODO: Get address from argument?
  :addr => "tcp://127.0.0.1:19150",
  :registry => {
    :adapter => conf.registry.adapter,
    :host => conf.registry.host,
    :port => conf.registry.port
  }
}

begin
  DCell.start(params)
  success("Started DCell succesfully")
#TODO: This error isn't rescued properly... figure out why and fix
rescue Exception => e
  failure "We were unable to connect to redis. It is probably not running or " +
          "its IP/port is configured wrong in /etc/openvnet/common.conf.", e
end

Vnet::Initializers::DB.run(conf.db_uri)

begin
  Vnet::Models::Base.db.test_connection
  success("Connected to the database successfully.")
rescue Exception => e
  failure "Unable to connect to the database. " +
          "Check your settings in /etc/openvnet/common.conf. ", e
end
